### ISSUE TITLE
Stale LOADED_SYMBOLS if function is recreated in another session

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#109]
Similar to the issue for transaction semantics around `CREATE OR REPLACE FUNCTION` for concurrent transactions, there's an issue with staleness in LOADED_SYMBOLS.

https://github.com/tcdi/plrust/blob/main/src/plrust.rs#L26-L28

If a session A executes a PL/Rust function foo, it loads/caches the symbol into `LOADED_SYMBOLS`.
However if another session B were to run `CREATE OR REPLACE foo` we never unload the symbols from session A meaning it'll execute with a stale function definition for the remainder of session A.

Initial thoughts are to check the TopTransactionXid and store it alongside LOADED_SYMBOLS? That way if the TopTransactionXid changes, it'll always LOAD the symbol again and prevent staleness to a certain extent

**Comment by anth0nyleung** [comment]
Not sure if PGX has api to assess TopTransactionId. But one way that i can think of to address this is to track the mtime of the source code / .so file in the in-memory map. On function execution, compare the in memory mtime of the function with the actual mtime of the source code / .so file. If the user function has been modified, the it should reload the function from the .so file.

**Comment by workingjubilee** [comment]
PGX can add the relevant header if necessary.

**Comment by workingjubilee** [comment]
I feel apprehensive about CREATE OR REPLACE FUNCTION in general, honestly. In the concurrent function creation case, with two sessions connected to Postgres, isn't this always a form of race condition?

We can create a coherent model for when to build, load, rebuild, and discard symbols, and use various tricks like symbol generations to make sure we're always using the correct symbol... but I don't think "two sessions open a transaction and try to commit creating the same function, and the second one will clobber the first, because even though they both think they are creating the same function, one will actually be OR REPLACE" is a situation where working around that with more and more epicycles is going to get us anywhere useful, as we then have to account for ROLLBACK transactions as well. Postgres avoids trying to unload symbols for similar reasons.

**Comment by anth0nyleung** [comment]
I think the issue does not necessary applies to two racing `CREATE OR REPLACE`. It could be some situation where one session performs a `CREATE OR REPLACE` and the function is up-to-date on this session. But on the other sessions the function is now stale.
```
# On Session1
postgres=> SELECT foo(1);
 foo
-----
   1
(1 row)

# On Session2
postgres=> SELECT foo(1);
 foo
-----
   1
(1 row)

# Update the function on Session1, the function is up-to-date
postgres=> CREATE OR REPLACE FUNCTION foo(i int) RETURNS INT AS
postgres-> $$
postgres$> Some(i.unwrap() + 1)
postgres$> $$ LANGUAGE plrust;
NOTICE:  INFO plrust::plrust: unloaded function
    at src/plrust.rs:40

CREATE FUNCTION
postgres=> SELECT foo (1);
 foo
-----
   2
(1 row)

# However in Session2, the function is stale
postgres=> SELECT foo(1);
 foo
-----
   1
(1 row)
```

For plpgsql, this is handled properly
```
# Session1
postgres=# SELECT test_plpgsql(1);
 test_plpgsql
--------------
            1
(1 row)

# Session2
postgres=# SELECT test_plpgsql(1);
 test_plpgsql
--------------
            1
(1 row)

# Update the function on Session1
postgres=# CREATE OR REPLACE FUNCTION test_plpgsql(i int)
  RETURNS int AS
$$
BEGIN
  RETURN i + 1;
END
$$ LANGUAGE plpgsql;
CREATE FUNCTION
postgres=# SELECT test_plpgsql(1);
 test_plpgsql
--------------
            2
(1 row)

# On Session2
postgres=# SELECT test_plpgsql(1);
 test_plpgsql
--------------
            2
(1 row)
```

**Comment by workingjubilee** [comment]
I know that part, I'm just annoyed because of the other implications.

e.g. whatever schema we use to approach this has to do something to avoid rebuilding and replacing the function and opening new sharedlibs with new symbols constantly or else it becomes distressingly plausible to just repeatedly issue CREATE OR REPLACE FUNCTION until the machine runs out of hard drive space and memory. But this becomes comparatively easier if we always know whether we're creating instance "generation 0" for a function or advancing the generation by 1.

**Comment by eeeebbbbrrrr** [comment]
This has been fixed.  We now track the `xmin` of the row from `pg_catalog.pg_proc`.  And if that's different than what we previously loaded we then (attempt to) unload the function and reload the new version.
