### ISSUE TITLE
Need to disallow Rust's `include_xxx!()` macros

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [tcdi/plrust#172]
This plrust function should not compile, let alone work:

```postgres
create function include_str() returns text language plrust as 
$$ 
   let s = include_str!("/etc/passwd"); 
   Ok(Some(s.into())) 
$$;
```

@workingjubilee is this something we can block in `postgrestd`?  It appears to be in `std`:  https://doc.rust-lang.org/std/macro.include_str.html

**Comment by eeeebbbbrrrr** [comment]
The more I think about it…

we shouldn’t support this on non-postgrestd targets either. 

Unfortunately, I don’t have an immediate idea how to block it. Is there a #[deny] lint for this?

**Comment by workingjubilee** [comment]
It looks like `include_str!` can only access files you have permission for.

```rust
   error: couldn't read /etc/shadow: Permission denied (os error 13)
     --> src/lib.rs:10:17
      |
   10 |         let s = include_str!("/etc/shadow");
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

   error: couldn't read /etc/shadow: Permission denied (os error 13)
     --> src/lib.rs:22:17
      |
   22 |         let s = include_str!("/etc/shadow");
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

   error: could not compile `plrust_fn_oid_16384_16446` due to 2 previous errors


Source Code:
   #![deny(unsafe_op_in_unsafe_fn)]
   pub mod opened {
       #[allow(unused_imports)]
       use pgx::prelude::*;
       #[pg_extern]
       fn plrust_fn_oid_16384_16446() -> ::std::result::Result<
           Option<String>,
           Box<dyn ::std::error::Error>,
       > {
           let s = include_str!("/etc/shadow");
           Ok(Some(s.into()))
       }
   }
   mod forbidden {
       #![forbid(unsafe_code)]
       #[allow(unused_imports)]
       use pgx::prelude::*;
       fn plrust_fn_oid_16384_16446() -> ::std::result::Result<
           Option<String>,
           Box<dyn ::std::error::Error>,
       > {
           let s = include_str!("/etc/shadow");
           Ok(Some(s.into()))
       }
   }


  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: plrust::user_crate::build::build_internal with db_oid=oid=#16384 fn_oid=oid=#16446 crate_dir=/tmp/plrust-tests.QKnS7epd2apD/plrust_fn_oid_16384_16446 target_dir=/tmp/plrust-tests.QKnS7epd2apD/target target_triple=x86_64-postgres-linux-gnu
      at plrust/src/user_crate/build.rs:84
   1: plrust::user_crate::build::build with db_oid=oid=#16384 fn_oid=oid=#16446 crate_dir=/tmp/plrust-tests.QKnS7epd2apD/plrust_fn_oid_16384_16446 target_dir=/tmp/plrust-tests.QKnS7epd2apD/target
      at plrust/src/user_crate/build.rs:61
   2: plrust::user_crate::build with db_oid=oid=#16384 fn_oid=oid=#16446 crate_dir=/tmp/plrust-tests.QKnS7epd2apD/plrust_fn_oid_16384_16446 target_dir=/tmp/plrust-tests.QKnS7epd2apD/target
      at plrust/src/user_crate/mod.rs:142
   3: plrust::plrust::compile_function with fn_oid=Oid(16446)
      at plrust/src/plrust.rs:103
   4: plrust::plrust_validator with fn_oid=Oid(16446) fcinfo=0x7fffb2f7ea20
      at plrust/src/lib.rs:158

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Postgres location: lib.rs:201
Rust location: SQL statement "
            create function include_str() returns text language plrust as 
            $$ 
                let s = include_str!("/etc/shadow");
                Ok(Some(s.into())) 
            $$;
        "
```

`/etc/shadow` being, unlike `/etc/passwd`, the file that actually contains naughty data like hashed passwords that users should not be able to read[^1]. So that's one layer of defense we retain: no magic ability to transgress standard Unix permissions.

This is a case of a more architecture-independent problem: the runtime architecture doesn't matter as much as the build-time capabilities of the compiler. The target std can be modified to change `include{,_str,_bytes}!` to compile errors, but that assumes that we aren't locking out desirable crates that use `include!`s in a benign way on their own source code (or, if we can figure out how to make "safe" build.rs execution, on generated code). Better to sacrifice those than leave this open, ofc.

[^1]: https://soatok.blog/2022/12/29/what-we-do-in-the-etc-shadow-cryptography-with-passwords/

**Comment by eeeebbbbrrrr** [comment]
Yeah, it can read anything the connected backend process can read.  And the problem with that is it basically allows a plrust function to slurp up anything in $PGDATA (the actual database files).

Thinking about this overnight, I now think it's fine that "untrusted" (ie, non-`postgrestd` targets) can do this.  They could do this anyways at runtime with `std::fs::read()`.

However, we can't allow "trusted", `postgrestd`-based targets to do this.  We *gotta* hack this out of `postgrestd`.

If that means 3rd party dependencies all of a sudden can't do this either, then I suppose we have to live with that.  And I know that `build.rs` and `#[proc_macros]` are still problems too since they execute actual code at compile time.  I don't know what we can do about that.

Part of me thinks that if you're using "trusted" plrust, then you need to tightly control the dependency allow-list, or not allow dependencies at all.  

I also think that the system administrator probably ought to somehow jail `cargo` such that it can't see outside the configured `plrust.work_dir`.  That, fortunately, isn't our problem.

Anyways, we need to tighten this up in `postgrestd` before a 1.0 release.

**Comment by workingjubilee** [comment]
> I also think that the system administrator probably ought to somehow jail cargo such that it can't see outside the configured plrust.work_dir. That, fortunately, isn't our problem.

...what if we can solve this by making it our problem? Or at least, cooperating with the DBA that configures PL/Rust in regards to solving this problem. We can, when spawning cargo, use the [Unix CommandExt](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html) to set the user ID, group ID, and process group ID of the process.

**Comment by eeeebbbbrrrr** [comment]
If Postgres ran as root, then using `setuid(2)` would be a great idea.  However, some non-root user can't just become a different non-root user.  There's no concept of "downgrading" privileges when you're not root.

The only things I can see that would work is 
- for "cargo.exe" to be jailed,
- controlled by SELinux or something similar,
- owned by some other user and have its sticky bit set, but that's still a sysadmin-type task; or...

Maybe we could have an optional GUC like `plrust.cargo_exe = 'sudo -u a_plrust_user cargo'`.  At least at that point the sysadmin only needs to `visudo`, which is probably something they're familiar with.

**Comment by workingjubilee** [comment]
We discussed this a bit on Discord and we still want to fix this but it's not "critical, fix yesterday" at the current moment so we can cogitate a bit. We don't want to have it be something that requires extensive configuration. As a result, blocking `include!` inside postgrestd is still in the lead at the moment, so I will look at that as a possible solution soon.

**Comment by thomcc** [comment]
I'm pretty sure we could forbid these by just switching https://github.com/tcdi/postgrestd/blob/eb07b1ca49e966cd06d12534a77b9db1f01f1bd3/library/core/src/macros/mod.rs#L1217 (and similar lines on `include_bytes!` and `include!`) to something like:

```rs
#[unstable(feature = "include_macros", issue = "none", reason = "no file access in postgrestd")]
```

We'd then need to add `#![feature(include_macros)]` to a bunch of postgrestd's internal crates because `std` needs it internally. I'm pretty sure this would work.

I'd make a PR for this but I'm neck deep in cross compilation testing and am unsure I have easy access to a machine that can test this.

**Comment by thomcc** [comment]
That doesn't quite work, because actually forbidding these is impossible -- pgx itself has a number of dependencies that use it internally. We'd need to find a way to allow it for only "approved" cases, which is substantially harder.

I wonder if we can allow `include_str!` but just make it return an empty string rather than being a builtin macro.

**Comment by thomcc** [comment]
Yes, that worked. https://github.com/tcdi/postgrestd/pull/23 has a fix for this.

**Comment by thomcc** [comment]
Failing test (which is fixed by https://github.com/tcdi/postgrestd/pull/23) in https://github.com/tcdi/plrust/pull/192.

**Comment by thomcc** [comment]
This is fixed by that PR. It doesn't cover `include!` (for source code inclusion -- the equivalent of `#include`), but it doesn't seem to possible to use that to read a file from disk in a manner usable programmatically.

Some thoughts on how we could address it if I've misjudged and it is actually possible to use `include!` in such a manner are [here](https://github.com/tcdi/postgrestd/pull/23#issuecomment-1411139228), but until it turns out to be possible, I'm not worried about it.
