### ISSUE TITLE
println! / dbg! allowed, impacts auditability

### ISSUE THREAD

**Issue by JohnHVancouver** [tcdi/plrust#222]
We currently allow dbg/eprint/eprintln/print/println to be called from PL/Rust. This allows directly writing to the log file which means it doesn't go through Postgres's logging infrastructure (log_min_messages, log_statement etc) and impacts audibility/parsing if needed.

```
2023-02-17 10:08:22.992 PST [66423] LOG:  logging to log through pgx macro
2023-02-17 10:08:22.992 PST [66423] STATEMENT:  select test_logging();
[src/lib.rs:12] "Writing through dbg" = "Writing through dbg"
Writing through println!
Writing through eprint
```

**Comment by workingjubilee** [comment]
Some options:
- We could try to lint these macros but the dependency use-case means that if we use a lint on the function crate, it's not going to affect the dependencies, but that means dependencies included now impact the logs
- Blocking them in all crates breaks dependencies, since `println!` is ubiquitous in the crates.io ecosystem
- It may be better to wrap Rust's stdout with something that prefixes the output
- Since deployments are recommended to not trivially use dependencies, and this is not trusted-PL-critical but rather a downstream concern, it may be easiest to, right now, shadow `println!` with another definition inside function crates: a macro that instead forwards it through `log!`

**Comment by thomcc** [comment]
We could also do this by adjusting https://github.com/tcdi/postgrestd/blob/1.67.1/library/std/src/io/stdio.rs#L17 to use a callback, and use set_output_capture to log with `log!` or something like that.
